In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 72 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.09 s


In [5]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

In [6]:
data * 10

array([[-2.0471,  4.7894, -5.1944],
       [-5.5573, 19.6578, 13.9341]])

In [7]:
data+data

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtpye

AttributeError: 'numpy.ndarray' object has no attribute 'dtpye'

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
data2 = [[1, 2, 3], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([list([1, 2, 3]), list([5, 6, 7, 8])], dtype=object)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(2,3)

TypeError: data type not understood

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
np.arange((2,3))

TypeError: arange: scalar arguments expected instead of a tuple.

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [24]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [27]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [28]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [29]:
arr ** 0.5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

In [30]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [32]:
arr=np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[5]

5

In [35]:
arr[3:7]

array([3, 4, 5, 6])

In [36]:
arr[8:9]=100

In [37]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7, 100,   9])

In [38]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [39]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [40]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [41]:
arr=np.array([1,10,100,200])
arr

array([  1,  10, 100, 200])

In [42]:
arr1=arr
arr1[1]=69
arr1

array([  1,  69, 100, 200])

In [43]:
arr

array([  1,  69, 100, 200])

In [44]:
arr=[1,10,100,200]
arr

[1, 10, 100, 200]

In [45]:
arr1=arr
arr1[1]=69
arr1

[1, 69, 100, 200]

In [46]:
arr

[1, 69, 100, 200]

In [47]:
dtpye(arr)

NameError: name 'dtpye' is not defined

In [48]:
arr.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [49]:
arr=arange(1,10)
arr

NameError: name 'arange' is not defined

In [50]:
arr=list(arange(0,10))
arr

NameError: name 'arange' is not defined

In [51]:
arr=list(range(0,10))
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
arr1=arr
arr1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
arr1[4]=100
arr1

[0, 1, 2, 3, 100, 5, 6, 7, 8, 9]

In [54]:
arr

[0, 1, 2, 3, 100, 5, 6, 7, 8, 9]

In [55]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [56]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
tt=arr3d[0].copy
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3d[0]=tt
arr3d

TypeError: int() argument must be a string, a bytes-like object or a number, not 'builtin_function_or_method'

In [61]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
tt=arr3d[0].copy
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3d[0]=tt
arr3d

TypeError: int() argument must be a string, a bytes-like object or a number, not 'builtin_function_or_method'

In [64]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
tt=arr3d[0].copy()
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[0]=tt
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[1,0]

array([7, 8, 9])

In [67]:
arr3d[1,0,0]

7

In [68]:
arr

[0, 1, 2, 3, 100, 5, 6, 7, 8, 9]

In [69]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [73]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr2d[2,:2]

array([7, 8])

In [75]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq

[7, 2, 3, 7, 5, 6, 0, 1]

In [76]:
seq[3:4] = [6, 3]
seq

[7, 2, 3, 6, 3, 5, 6, 0, 1]

In [77]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[3:5] = [6, 3]
seq

[7, 2, 3, 6, 3, 6, 0, 1]

In [79]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[3:5] = [60, 30]
seq

[7, 2, 3, 60, 30, 6, 0, 1]

In [80]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[3:6] = [60, 30]
seq

[7, 2, 3, 60, 30, 0, 1]

In [1]:
seq

NameError: name 'seq' is not defined

In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,:1]

NameError: name 'np' is not defined

In [3]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,:1]

array([4])

In [4]:
arr2d[1,:2]

array([4, 5])

In [5]:
arr2d[2,:2]

array([7, 8])

In [6]:
arr2d[:2,2]

array([3, 6])

In [7]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [8]:
arr2d[:1,:]

array([[1, 2, 3]])

In [9]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2d{,:2}

SyntaxError: invalid syntax (<ipython-input-11-869a8b570797>, line 1)

In [12]:
arr2d[,:2]

SyntaxError: invalid syntax (<ipython-input-12-31c5fc265459>, line 1)

In [13]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [14]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [15]:
data

array([[ 0.32236002, -1.62387732,  0.25989231, -0.09446795],
       [-0.08512082,  0.13063859,  1.62093705, -0.26916774],
       [ 1.02959457,  0.45989103,  0.80335047, -0.70921095],
       [ 0.28509789, -1.75507967,  0.1039922 , -0.37528615],
       [-0.75945113,  0.22686741, -0.59953553,  0.96561333],
       [-1.44761735, -0.60398338,  0.94956528,  0.07716678],
       [-0.44982049,  0.20670738, -2.25580846, -0.63830316]])

In [16]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [17]:
data[names == 'Bob']

array([[ 0.32236002, -1.62387732,  0.25989231, -0.09446795],
       [ 0.28509789, -1.75507967,  0.1039922 , -0.37528615]])

In [18]:
data[names == 'Bob',2:]

array([[ 0.25989231, -0.09446795],
       [ 0.1039922 , -0.37528615]])

In [19]:
data[names == 'Bob',3]

array([-0.09446795, -0.37528615])

In [20]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [21]:
arrar[[2,4]]

NameError: name 'arrar' is not defined

In [22]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [23]:
arr[[4, 3, 0, 8]]

IndexError: index 8 is out of bounds for axis 0 with size 8

In [24]:
arr[[4, 10, 0, 6]]

IndexError: index 10 is out of bounds for axis 0 with size 8

In [25]:
arr[[-2,-3,-5],:3]

array([[6., 6., 6.],
       [5., 5., 5.],
       [3., 3., 3.]])

In [26]:
arr=np.arange(32)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [27]:
arr=np.arange.reshape(4,8)

AttributeError: 'builtin_function_or_method' object has no attribute 'reshape'

In [28]:
arr=np.arange(32).reshape(4,8)

In [29]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [30]:
arr=np.arange(32).reshape((4,8))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [31]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

IndexError: index 5 is out of bounds for axis 0 with size 4

In [32]:
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [33]:
arr[3,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [34]:
arr[[3,4]]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
arr[[3],[4]]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [36]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [37]:
arr[[1], [0]]

array([4])

In [38]:
arr[[3],[3]]

array([15])

In [39]:
arr[3,3]

15

In [40]:
arr=np.arange(15).reshape(5,3)

In [41]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
arr.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [43]:
np.dot(arr.T, arr)

array([[270, 300, 330],
       [300, 335, 370],
       [330, 370, 410]])

In [44]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [45]:
arr[0]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [47]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [48]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [49]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5, 1.0, 'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [50]:
plt.draw()

<Figure size 432x288 with 0 Axes>

In [51]:
plt.close('all')

In [1]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

NameError: name 'np' is not defined

In [2]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [3]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [4]:
arr = np.random.randn(4, 4)
np.where(arr > 0, 2, -2)

array([[-2, -2, -2, -2],
       [ 2,  2, -2, -2],
       [-2, -2,  2,  2],
       [-2, -2, -2, -2]])

In [5]:
arr = np.random.randn(4, 4)
arr

array([[-0.63078045, -0.67704499,  0.24602684, -0.98600696],
       [ 1.43136554, -1.50370675,  0.43251851, -0.60254188],
       [ 0.82320681, -0.47500215,  2.35668059,  0.48924472],
       [-1.83026047,  0.64899961,  0.06548288,  0.54247977]])

In [6]:
np.where(arr > 0, 20, 8)

array([[ 8,  8, 20,  8],
       [20,  8, 20,  8],
       [20,  8, 20, 20],
       [ 8, 20, 20, 20]])

In [7]:
arr

array([[-0.63078045, -0.67704499,  0.24602684, -0.98600696],
       [ 1.43136554, -1.50370675,  0.43251851, -0.60254188],
       [ 0.82320681, -0.47500215,  2.35668059,  0.48924472],
       [-1.83026047,  0.64899961,  0.06548288,  0.54247977]])

In [8]:
np.where(arr > 0, 100, arr)

array([[ -0.63078045,  -0.67704499, 100.        ,  -0.98600696],
       [100.        ,  -1.50370675, 100.        ,  -0.60254188],
       [100.        ,  -0.47500215, 100.        , 100.        ],
       [ -1.83026047, 100.        , 100.        , 100.        ]])

In [9]:
arr=np.arange(12).reshape(3,4)

In [10]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
arr.sum()

66

In [12]:
arr.mean()

5.5

In [13]:
arr.sum(axis=0)

array([12, 15, 18, 21])

In [14]:
arr.sum(axis=1)

array([ 6, 22, 38])

In [15]:
arr[1].sum()

22

In [16]:
arr[:,2]

array([ 2,  6, 10])

In [17]:
arr[:,2].sum()

18

In [18]:
arr[1]

array([4, 5, 6, 7])

In [19]:
arr[1,:]

array([4, 5, 6, 7])

In [20]:
arr.sum(1)

array([ 6, 22, 38])

In [21]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

48

In [22]:
arr = np.random.randn(100)
arr

array([-0.2923621 ,  0.90210766, -0.18227294, -0.00725116,  0.77778282,
        0.36583229, -1.34664817, -0.11318825, -2.16298748, -0.15577878,
       -0.47810898,  0.52855167,  0.31426791,  2.45661991, -1.10359055,
       -0.69837281,  0.04411346, -0.39439567, -1.49352746, -0.3177152 ,
       -0.4949718 ,  0.88916614,  0.62699019, -0.39573981,  0.83151332,
       -0.19397883,  1.29835064, -1.62754937,  0.05841909,  0.43151792,
       -0.75445983, -0.0812917 , -0.21494047,  1.85333252,  0.46906225,
        0.09213437, -1.73826395,  1.4358649 , -0.69454042,  0.05046572,
        0.06289963, -0.51480064,  0.37865295,  0.82992685, -0.21905627,
        1.04636564,  2.19730203, -0.56133347,  0.12061963, -1.02904814,
       -0.65530861,  1.71257868,  1.99940131,  0.0663788 ,  0.95123945,
        0.28882656,  2.07998942, -1.30544922, -0.09717612, -0.51020785,
       -0.09180654, -0.99915936,  1.98105281,  1.28307448,  0.19079034,
       -1.76888675,  0.16696711, -1.3138053 ,  0.17540835,  0.13

In [23]:
(arr > 0).sum()

47

In [24]:
bools = np.array([False, False, True, False])
bools.any()

True

In [25]:
bools.all()

False

In [26]:
arr=np.random.randn(6)

In [27]:
arr

array([-0.1435631 ,  0.86314184,  0.1636319 ,  1.44489018, -0.47023854,
        0.88679917])

In [28]:
arr.sort()

In [29]:
arr

array([-0.47023854, -0.1435631 ,  0.1636319 ,  0.86314184,  0.88679917,
        1.44489018])

In [30]:
arr=np.random.randn(5,3)
arr

array([[-1.02781958,  2.13793695, -1.14210506],
       [-0.43730243,  0.53901089, -0.25820395],
       [-0.12475302,  0.97187407,  0.16106189],
       [ 1.01417641,  0.86815712,  2.58059661],
       [-0.76710185,  1.76587647,  0.06012309]])

In [31]:
arr.sort(1)
arr

array([[-1.14210506, -1.02781958,  2.13793695],
       [-0.43730243, -0.25820395,  0.53901089],
       [-0.12475302,  0.16106189,  0.97187407],
       [ 0.86815712,  1.01417641,  2.58059661],
       [-0.76710185,  0.06012309,  1.76587647]])

In [32]:
arr.sort()
arr

array([[-1.14210506, -1.02781958,  2.13793695],
       [-0.43730243, -0.25820395,  0.53901089],
       [-0.12475302,  0.16106189,  0.97187407],
       [ 0.86815712,  1.01417641,  2.58059661],
       [-0.76710185,  0.06012309,  1.76587647]])

In [33]:
arr=np.random.randn(3,2)
arr

array([[ 0.78115256,  0.14604484],
       [-0.50170993,  0.25233858],
       [ 0.37657625,  1.34410976]])

In [34]:
arr.sort()

In [35]:
arr

array([[ 0.14604484,  0.78115256],
       [-0.50170993,  0.25233858],
       [ 0.37657625,  1.34410976]])

In [36]:
arr.sort(1)
arr

array([[ 0.14604484,  0.78115256],
       [-0.50170993,  0.25233858],
       [ 0.37657625,  1.34410976]])

In [37]:
arr.sort(0)
arr

array([[-0.50170993,  0.25233858],
       [ 0.14604484,  0.78115256],
       [ 0.37657625,  1.34410976]])

In [38]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.5574143071842643