In [1]:
import numpy as np
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [2]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArray.__new_

In [3]:
a.ndim

1

In [4]:
a.shape

(4,)

In [5]:
len(a)

4

In [6]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [12]:
a = np.random.rand(4)       # [0, 1] 的均匀分布
a

array([0.44631306, 0.23881999, 0.83024573, 0.74476418])

In [13]:
b = np.random.randn(4)      # 高斯
b

array([-0.21754548,  2.63779121, -1.74213763, -0.09443481])